package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Altrntv generated by hbm2java
 */
@Entity
@Table(name="altrntv"
    ,catalog="mca2"
)
public class Altrntv  implements java.io.Serializable {


     private Long idAltrntv;
     private String snm;
     private String nm;
     private String dscr;
     private Long idPrblm;
     private Long seq;
     private Set<AltrntvVl> altrntvVls = new HashSet<AltrntvVl>(0);
     private Set<ItrAlter> itrAlters = new HashSet<ItrAlter>(0);

    public Altrntv() {
    }

    public Altrntv(String snm, String nm, String dscr, Long idPrblm, Long seq, Set<AltrntvVl> altrntvVls, Set<ItrAlter> itrAlters) {
       this.snm = snm;
       this.nm = nm;
       this.dscr = dscr;
       this.idPrblm = idPrblm;
       this.seq = seq;
       this.altrntvVls = altrntvVls;
       this.itrAlters = itrAlters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_altrntv", unique=true, nullable=false)
    public Long getIdAltrntv() {
        return this.idAltrntv;
    }
    
    public void setIdAltrntv(Long idAltrntv) {
        this.idAltrntv = idAltrntv;
    }
    
    @Column(name="snm", length=16)
    public String getSnm() {
        return this.snm;
    }
    
    public void setSnm(String snm) {
        this.snm = snm;
    }
    
    @Column(name="nm", length=128)
    public String getNm() {
        return this.nm;
    }
    
    public void setNm(String nm) {
        this.nm = nm;
    }
    
    @Column(name="dscr", length=2048)
    public String getDscr() {
        return this.dscr;
    }
    
    public void setDscr(String dscr) {
        this.dscr = dscr;
    }
    
    @Column(name="id_prblm")
    public Long getIdPrblm() {
        return this.idPrblm;
    }
    
    public void setIdPrblm(Long idPrblm) {
        this.idPrblm = idPrblm;
    }
    
    @Column(name="seq")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="altrntv")
    public Set<AltrntvVl> getAltrntvVls() {
        return this.altrntvVls;
    }
    
    public void setAltrntvVls(Set<AltrntvVl> altrntvVls) {
        this.altrntvVls = altrntvVls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="altrntv")
    public Set<ItrAlter> getItrAlters() {
        return this.itrAlters;
    }
    
    public void setItrAlters(Set<ItrAlter> itrAlters) {
        this.itrAlters = itrAlters;
    }




}


