package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AltrntvVl generated by hbm2java
 */
@Entity
@Table(name="altrntv_vl"
    ,catalog="mca2"
)
public class AltrntvVl  implements java.io.Serializable {


     private AltrntvVlId id;
     private Altrntv altrntv;
     private Atrbt atrbt;
     private Float orgValue;
     private Float normValue;

    public AltrntvVl() {
    }

	
    public AltrntvVl(AltrntvVlId id, Altrntv altrntv, Atrbt atrbt) {
        this.id = id;
        this.altrntv = altrntv;
        this.atrbt = atrbt;
    }
    public AltrntvVl(AltrntvVlId id, Altrntv altrntv, Atrbt atrbt, Float orgValue, Float normValue) {
       this.id = id;
       this.altrntv = altrntv;
       this.atrbt = atrbt;
       this.orgValue = orgValue;
       this.normValue = normValue;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idAltrntv", column=@Column(name="id_altrntv", nullable=false) ), 
        @AttributeOverride(name="idAtrbt", column=@Column(name="id_atrbt", nullable=false) ) } )
    public AltrntvVlId getId() {
        return this.id;
    }
    
    public void setId(AltrntvVlId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_altrntv", nullable=false, insertable=false, updatable=false)
    public Altrntv getAltrntv() {
        return this.altrntv;
    }
    
    public void setAltrntv(Altrntv altrntv) {
        this.altrntv = altrntv;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_atrbt", nullable=false, insertable=false, updatable=false)
    public Atrbt getAtrbt() {
        return this.atrbt;
    }
    
    public void setAtrbt(Atrbt atrbt) {
        this.atrbt = atrbt;
    }
    
    @Column(name="org_value", precision=12, scale=0)
    public Float getOrgValue() {
        return this.orgValue;
    }
    
    public void setOrgValue(Float orgValue) {
        this.orgValue = orgValue;
    }
    
    @Column(name="norm_value", precision=12, scale=0)
    public Float getNormValue() {
        return this.normValue;
    }
    
    public void setNormValue(Float normValue) {
        this.normValue = normValue;
    }




}


