package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AltrntvVlId generated by hbm2java
 */
@Embeddable
public class AltrntvVlId  implements java.io.Serializable {


     private Long idAltrntv;
     private Long idAtrbt;

    public AltrntvVlId() {
    }

    public AltrntvVlId(Long idAltrntv, Long idAtrbt) {
       this.idAltrntv = idAltrntv;
       this.idAtrbt = idAtrbt;
    }
   

    @Column(name="id_altrntv", nullable=false)
    public Long getIdAltrntv() {
        return this.idAltrntv;
    }
    
    public void setIdAltrntv(Long idAltrntv) {
        this.idAltrntv = idAltrntv;
    }

    @Column(name="id_atrbt", nullable=false)
    public Long getIdAtrbt() {
        return this.idAtrbt;
    }
    
    public void setIdAtrbt(Long idAtrbt) {
        this.idAtrbt = idAtrbt;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AltrntvVlId) ) return false;
		 AltrntvVlId castOther = ( AltrntvVlId ) other; 
         
		 return ( (this.getIdAltrntv()==castOther.getIdAltrntv()) || ( this.getIdAltrntv()!=null && castOther.getIdAltrntv()!=null && this.getIdAltrntv().equals(castOther.getIdAltrntv()) ) )
 && ( (this.getIdAtrbt()==castOther.getIdAtrbt()) || ( this.getIdAtrbt()!=null && castOther.getIdAtrbt()!=null && this.getIdAtrbt().equals(castOther.getIdAtrbt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdAltrntv() == null ? 0 : this.getIdAltrntv().hashCode() );
         result = 37 * result + ( getIdAtrbt() == null ? 0 : this.getIdAtrbt().hashCode() );
         return result;
   }   


}


