package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Atrbt generated by hbm2java
 */
@Entity
@Table(name="atrbt"
    ,catalog="mca2"
)
public class Atrbt  implements java.io.Serializable {


     private Long idAtrbt;
     private Prblm prblm;
     private String snm;
     private String nm;
     private String dscr;
     private String unit;
     private Set<Crtrn> crtrns = new HashSet<Crtrn>(0);
     private Set<AltrntvVl> altrntvVls = new HashSet<AltrntvVl>(0);


    public Atrbt() {
    }


   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_atrbt", unique=true, nullable=false)
    public Long getIdAtrbt() {
        return this.idAtrbt;
    }
    
    public void setIdAtrbt(Long idAtrbt) {
        this.idAtrbt = idAtrbt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_prblm")
    public Prblm getPrblm() {
        return this.prblm;
    }
    
    public void setPrblm(Prblm prblm) {
        this.prblm = prblm;
    }
    
    @Column(name="snm", length=16)
    public String getSnm() {
        return this.snm;
    }
    
    public void setSnm(String snm) {
        this.snm = snm;
    }
    
    @Column(name="nm", length=128)
    public String getNm() {
        return this.nm;
    }
    
    public void setNm(String nm) {
        this.nm = nm;
    }
    
    @Column(name="dscr", length=2048)
    public String getDscr() {
        return this.dscr;
    }
    
    public void setDscr(String dscr) {
        this.dscr = dscr;
    }
    
    @Column(name="unit", length=64)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="atrbt")
    public Set<Crtrn> getCrtrns() {
        return this.crtrns;
    }
    
    public void setCrtrns(Set<Crtrn> crtrns) {
        this.crtrns = crtrns;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="atrbt")
    public Set<AltrntvVl> getAltrntvVls() {
        return this.altrntvVls;
    }
    
    public void setAltrntvVls(Set<AltrntvVl> altrntvVls) {
        this.altrntvVls = altrntvVls;
    }




}


