package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Crtrn generated by hbm2java
 */
@Entity
@Table(name="crtrn"
    ,catalog="mca2"
)
public class Crtrn  implements java.io.Serializable {


     private Long idCrtrn;
     private Atrbt atrbt;
     private Instnc instnc;
     private Crtrn crtrn;
     private String snm;
     private String nm;
     private String dscr;
     private String type;
     private Float orgTarget;
     private Float orgValueMin;
     private Float orgValueMax;
     private Long seq;
     private Long lvl;
     private Long topSet;
     private Long idOutvar;
     private Long idVar;
     private Long buttonDisplay;
     private Set<Crtrn> crtrns = new HashSet<Crtrn>(0);
     private Set<ItrBoxplot> itrBoxplots = new HashSet<ItrBoxplot>(0);
     private Set<ItrDots> itrDotses = new HashSet<ItrDots>(0);

    public Crtrn() {
    }

    public Crtrn(Atrbt atrbt, Instnc instnc, Crtrn crtrn, String snm, String nm, String dscr, String type, Float orgTarget, Float orgValueMin, Float orgValueMax, Long seq, Long lvl, Long topSet, Long idOutvar, Long idVar, Long buttonDisplay, Set<Crtrn> crtrns, Set<ItrBoxplot> itrBoxplots, Set<ItrDots> itrDotses) {
       this.atrbt = atrbt;
       this.instnc = instnc;
       this.crtrn = crtrn;
       this.snm = snm;
       this.nm = nm;
       this.dscr = dscr;
       this.type = type;
       this.orgTarget = orgTarget;
       this.orgValueMin = orgValueMin;
       this.orgValueMax = orgValueMax;
       this.seq = seq;
       this.lvl = lvl;
       this.topSet = topSet;
       this.idOutvar = idOutvar;
       this.idVar = idVar;
       this.buttonDisplay = buttonDisplay;
       this.crtrns = crtrns;
       this.itrBoxplots = itrBoxplots;
       this.itrDotses = itrDotses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_crtrn", unique=true, nullable=false)
    public Long getIdCrtrn() {
        return this.idCrtrn;
    }
    
    public void setIdCrtrn(Long idCrtrn) {
        this.idCrtrn = idCrtrn;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_atrbt")
    public Atrbt getAtrbt() {
        return this.atrbt;
    }
    
    public void setAtrbt(Atrbt atrbt) {
        this.atrbt = atrbt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_instnc")
    public Instnc getInstnc() {
        return this.instnc;
    }
    
    public void setInstnc(Instnc instnc) {
        this.instnc = instnc;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent")
    public Crtrn getCrtrn() {
        return this.crtrn;
    }
    
    public void setCrtrn(Crtrn crtrn) {
        this.crtrn = crtrn;
    }
    
    @Column(name="snm", length=16)
    public String getSnm() {
        return this.snm;
    }
    
    public void setSnm(String snm) {
        this.snm = snm;
    }
    
    @Column(name="nm", length=128)
    public String getNm() {
        return this.nm;
    }
    
    public void setNm(String nm) {
        this.nm = nm;
    }
    
    @Column(name="dscr", length=2048)
    public String getDscr() {
        return this.dscr;
    }
    
    public void setDscr(String dscr) {
        this.dscr = dscr;
    }
    
    @Column(name="type", length=6)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    
    @Column(name="org_target", precision=12, scale=0)
    public Float getOrgTarget() {
        return this.orgTarget;
    }
    
    public void setOrgTarget(Float orgTarget) {
        this.orgTarget = orgTarget;
    }
    
    @Column(name="org_value_min", precision=12, scale=0)
    public Float getOrgValueMin() {
        return this.orgValueMin;
    }
    
    public void setOrgValueMin(Float orgValueMin) {
        this.orgValueMin = orgValueMin;
    }
    
    @Column(name="org_value_max", precision=12, scale=0)
    public Float getOrgValueMax() {
        return this.orgValueMax;
    }
    
    public void setOrgValueMax(Float orgValueMax) {
        this.orgValueMax = orgValueMax;
    }
    
    @Column(name="seq")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }
    
    @Column(name="lvl")
    public Long getLvl() {
        return this.lvl;
    }
    
    public void setLvl(Long lvl) {
        this.lvl = lvl;
    }
    
    @Column(name="top_set")
    public Long getTopSet() {
        return this.topSet;
    }
    
    public void setTopSet(Long topSet) {
        this.topSet = topSet;
    }
    
    @Column(name="id_outvar")
    public Long getIdOutvar() {
        return this.idOutvar;
    }
    
    public void setIdOutvar(Long idOutvar) {
        this.idOutvar = idOutvar;
    }
    
    @Column(name="id_var")
    public Long getIdVar() {
        return this.idVar;
    }
    
    public void setIdVar(Long idVar) {
        this.idVar = idVar;
    }
    
    @Column(name="button_display")
    public Long getButtonDisplay() {
        return this.buttonDisplay;
    }
    
    public void setButtonDisplay(Long buttonDisplay) {
        this.buttonDisplay = buttonDisplay;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="crtrn")
    public Set<Crtrn> getCrtrns() {
        return this.crtrns;
    }
    
    public void setCrtrns(Set<Crtrn> crtrns) {
        this.crtrns = crtrns;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="crtrn")
    public Set<ItrBoxplot> getItrBoxplots() {
        return this.itrBoxplots;
    }
    
    public void setItrBoxplots(Set<ItrBoxplot> itrBoxplots) {
        this.itrBoxplots = itrBoxplots;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="crtrn")
    public Set<ItrDots> getItrDotses() {
        return this.itrDotses;
    }
    
    public void setItrDotses(Set<ItrDots> itrDotses) {
        this.itrDotses = itrDotses;
    }




}


