package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EntHnt generated by hbm2java
 */
@Entity
@Table(name="ent_hnt"
    ,catalog="mca2"
)
public class EntHnt  implements java.io.Serializable {


     private EntHntId id;
     private String hnt;

    public EntHnt() {
    }

	
    public EntHnt(EntHntId id) {
        this.id = id;
    }
    public EntHnt(EntHntId id, String hnt) {
       this.id = id;
       this.hnt = hnt;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idEnt", column=@Column(name="id_ent", nullable=false) ), 
        @AttributeOverride(name="seq", column=@Column(name="seq", nullable=false) ) } )
    public EntHntId getId() {
        return this.id;
    }
    
    public void setId(EntHntId id) {
        this.id = id;
    }
    
    @Column(name="hnt", length=128)
    public String getHnt() {
        return this.hnt;
    }
    
    public void setHnt(String hnt) {
        this.hnt = hnt;
    }




}


