package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Itr generated by hbm2java
 */
@Entity
@Table(name="itr"
    ,catalog="mca2"
)
public class Itr  implements java.io.Serializable {


     private Long idItr;
     private Anlz anlz;
     private Usr usr;
     private Itr itr;
     private Long idMethod;
     private Date created;
     private Date lastmdfy;
     private Long status;
     private String note;
     private Set<Itr> itrs = new HashSet<Itr>(0);
     private Set<ItrDots> itrDotses = new HashSet<ItrDots>(0);
     private Set<ItrEntVl> itrEntVls = new HashSet<ItrEntVl>(0);
     private Set<ItrBoxplot> itrBoxplots = new HashSet<ItrBoxplot>(0);
     private Set<ItrMsg> itrMsgs = new HashSet<ItrMsg>(0);
     private Set<ItrAlter> itrAlters = new HashSet<ItrAlter>(0);

    public Itr() {
    }

    public Itr(Anlz anlz, Usr usr, Itr itr, Long idMethod, Date created, Date lastmdfy, Long status, String note, Set<Itr> itrs, Set<ItrDots> itrDotses, Set<ItrEntVl> itrEntVls, Set<ItrBoxplot> itrBoxplots, Set<ItrMsg> itrMsgs, Set<ItrAlter> itrAlters) {
       this.anlz = anlz;
       this.usr = usr;
       this.itr = itr;
       this.idMethod = idMethod;
       this.created = created;
       this.lastmdfy = lastmdfy;
       this.status = status;
       this.note = note;
       this.itrs = itrs;
       this.itrDotses = itrDotses;
       this.itrEntVls = itrEntVls;
       this.itrBoxplots = itrBoxplots;
       this.itrMsgs = itrMsgs;
       this.itrAlters = itrAlters;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_itr", unique=true, nullable=false)
    public Long getIdItr() {
        return this.idItr;
    }
    
    public void setIdItr(Long idItr) {
        this.idItr = idItr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_anlz")
    public Anlz getAnlz() {
        return this.anlz;
    }
    
    public void setAnlz(Anlz anlz) {
        this.anlz = anlz;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usr")
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent")
    public Itr getItr() {
        return this.itr;
    }
    
    public void setItr(Itr itr) {
        this.itr = itr;
    }
    
    @Column(name="id_method")
    public Long getIdMethod() {
        return this.idMethod;
    }
    
    public void setIdMethod(Long idMethod) {
        this.idMethod = idMethod;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastmdfy", length=19)
    public Date getLastmdfy() {
        return this.lastmdfy;
    }
    
    public void setLastmdfy(Date lastmdfy) {
        this.lastmdfy = lastmdfy;
    }
    
    @Column(name="status")
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    
    @Column(name="note", length=2048)
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itr")
    public Set<Itr> getItrs() {
        return this.itrs;
    }
    
    public void setItrs(Set<Itr> itrs) {
        this.itrs = itrs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itr")
    public Set<ItrDots> getItrDotses() {
        return this.itrDotses;
    }
    
    public void setItrDotses(Set<ItrDots> itrDotses) {
        this.itrDotses = itrDotses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itr")
    public Set<ItrEntVl> getItrEntVls() {
        return this.itrEntVls;
    }
    
    public void setItrEntVls(Set<ItrEntVl> itrEntVls) {
        this.itrEntVls = itrEntVls;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itr")
    public Set<ItrBoxplot> getItrBoxplots() {
        return this.itrBoxplots;
    }
    
    public void setItrBoxplots(Set<ItrBoxplot> itrBoxplots) {
        this.itrBoxplots = itrBoxplots;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itr")
    public Set<ItrMsg> getItrMsgs() {
        return this.itrMsgs;
    }
    
    public void setItrMsgs(Set<ItrMsg> itrMsgs) {
        this.itrMsgs = itrMsgs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="itr")
    public Set<ItrAlter> getItrAlters() {
        return this.itrAlters;
    }
    
    public void setItrAlters(Set<ItrAlter> itrAlters) {
        this.itrAlters = itrAlters;
    }




}


