package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItrAlter generated by hbm2java
 */
@Entity
@Table(name="itr_alter"
    ,catalog="mca2"
)
public class ItrAlter  implements java.io.Serializable {


     private ItrAlterId id;
     private Altrntv altrntv;
     private Atrbt atrbt;
     private Itr itr;
     private Long pos;
     private Float caf;

    public ItrAlter() {
    }

	
    public ItrAlter(ItrAlterId id, Altrntv altrntv, Atrbt atrbt, Itr itr) {
        this.id = id;
        this.altrntv = altrntv;
        this.atrbt = atrbt;
        this.itr = itr;
    }
    public ItrAlter(ItrAlterId id, Altrntv altrntv, Atrbt atrbt, Itr itr, Long pos, Float caf) {
       this.id = id;
       this.altrntv = altrntv;
       this.atrbt = atrbt;
       this.itr = itr;
       this.pos = pos;
       this.caf = caf;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idItr", column=@Column(name="id_itr", nullable=false) ), 
        @AttributeOverride(name="idAtrbt", column=@Column(name="id_atrbt", nullable=false) ), 
        @AttributeOverride(name="idAltrntv", column=@Column(name="id_altrntv", nullable=false) ) } )
    public ItrAlterId getId() {
        return this.id;
    }
    
    public void setId(ItrAlterId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_altrntv", nullable=false, insertable=false, updatable=false)
    public Altrntv getAltrntv() {
        return this.altrntv;
    }
    
    public void setAltrntv(Altrntv altrntv) {
        this.altrntv = altrntv;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_atrbt", nullable=false, insertable=false, updatable=false)
    public Atrbt getAtrbt() {
        return this.atrbt;
    }
    
    public void setAtrbt(Atrbt atrbt) {
        this.atrbt = atrbt;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_itr", nullable=false, insertable=false, updatable=false)
    public Itr getItr() {
        return this.itr;
    }
    
    public void setItr(Itr itr) {
        this.itr = itr;
    }
    
    @Column(name="pos")
    public Long getPos() {
        return this.pos;
    }
    
    public void setPos(Long pos) {
        this.pos = pos;
    }
    
    @Column(name="caf", precision=12, scale=0)
    public Float getCaf() {
        return this.caf;
    }
    
    public void setCaf(Float caf) {
        this.caf = caf;
    }




}


