package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItrAlterId generated by hbm2java
 */
@Embeddable
public class ItrAlterId  implements java.io.Serializable {


     private Long idItr;
     private Long idCrtrn;
     private Long idAltrntv;

    public ItrAlterId() {
    }

    public ItrAlterId(Long idItr, Long idCrtrn, Long idAltrntv) {
       this.idItr = idItr;
       this.idCrtrn = idCrtrn;
       this.idAltrntv = idAltrntv;
    }
   

    @Column(name="id_itr", nullable=false)
    public Long getIdItr() {
        return this.idItr;
    }
    
    public void setIdItr(Long idItr) {
        this.idItr = idItr;
    }

    @Column(name="id_crtrn", nullable=false)
    public Long getIdCrtrn() {
        return this.idCrtrn;
    }
    
    public void setIdCrtrn(Long idCrtrn) {
        this.idCrtrn = idCrtrn;
    }

    @Column(name="id_altrntv", nullable=false)
    public Long getIdAltrntv() {
        return this.idAltrntv;
    }
    
    public void setIdAltrntv(Long idAltrntv) {
        this.idAltrntv = idAltrntv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItrAlterId) ) return false;
		 ItrAlterId castOther = ( ItrAlterId ) other; 
         
		 return ( (this.getIdItr()==castOther.getIdItr()) || ( this.getIdItr()!=null && castOther.getIdItr()!=null && this.getIdItr().equals(castOther.getIdItr()) ) )
 && ( (this.getIdCrtrn()==castOther.getIdCrtrn()) || ( this.getIdCrtrn()!=null && castOther.getIdCrtrn()!=null && this.getIdCrtrn().equals(castOther.getIdCrtrn()) ) )
 && ( (this.getIdAltrntv()==castOther.getIdAltrntv()) || ( this.getIdAltrntv()!=null && castOther.getIdAltrntv()!=null && this.getIdAltrntv().equals(castOther.getIdAltrntv()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdItr() == null ? 0 : this.getIdItr().hashCode() );
         result = 37 * result + ( getIdCrtrn() == null ? 0 : this.getIdCrtrn().hashCode() );
         result = 37 * result + ( getIdAltrntv() == null ? 0 : this.getIdAltrntv().hashCode() );
         return result;
   }   


}


