package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItrBoxplotId generated by hbm2java
 */
@Embeddable
public class ItrBoxplotId  implements java.io.Serializable {


     private Long idItr;
     private Long idCrtrn;

    public ItrBoxplotId() {
    }

    public ItrBoxplotId(Long idItr, Long idCrtrn) {
       this.idItr = idItr;
       this.idCrtrn = idCrtrn;
    }
   

    @Column(name="id_itr", nullable=false)
    public Long getIdItr() {
        return this.idItr;
    }
    
    public void setIdItr(Long idItr) {
        this.idItr = idItr;
    }

    @Column(name="id_crtrn", nullable=false)
    public Long getIdCrtrn() {
        return this.idCrtrn;
    }
    
    public void setIdCrtrn(Long idCrtrn) {
        this.idCrtrn = idCrtrn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItrBoxplotId) ) return false;
		 ItrBoxplotId castOther = ( ItrBoxplotId ) other; 
         
		 return ( (this.getIdItr()==castOther.getIdItr()) || ( this.getIdItr()!=null && castOther.getIdItr()!=null && this.getIdItr().equals(castOther.getIdItr()) ) )
 && ( (this.getIdCrtrn()==castOther.getIdCrtrn()) || ( this.getIdCrtrn()!=null && castOther.getIdCrtrn()!=null && this.getIdCrtrn().equals(castOther.getIdCrtrn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdItr() == null ? 0 : this.getIdItr().hashCode() );
         result = 37 * result + ( getIdCrtrn() == null ? 0 : this.getIdCrtrn().hashCode() );
         return result;
   }   


}


