package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItrDots generated by hbm2java
 */
@Entity
@Table(name="itr_dots"
    ,catalog="mca2"
)
public class ItrDots  implements java.io.Serializable {


     private ItrDotsId id;
     private Itr itr;
     private Crtrn crtrn;
     private String label;
     private Long ndots;

    public ItrDots() {
    }

	
    public ItrDots(ItrDotsId id, Itr itr, Crtrn crtrn) {
        this.id = id;
        this.itr = itr;
        this.crtrn = crtrn;
    }
    public ItrDots(ItrDotsId id, Itr itr, Crtrn crtrn, String label, Long ndots) {
       this.id = id;
       this.itr = itr;
       this.crtrn = crtrn;
       this.label = label;
       this.ndots = ndots;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idItr", column=@Column(name="id_itr", nullable=false) ), 
        @AttributeOverride(name="idCrtrn", column=@Column(name="id_crtrn", nullable=false) ), 
        @AttributeOverride(name="pos", column=@Column(name="pos", nullable=false) ) } )
    public ItrDotsId getId() {
        return this.id;
    }
    
    public void setId(ItrDotsId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_itr", nullable=false, insertable=false, updatable=false)
    public Itr getItr() {
        return this.itr;
    }
    
    public void setItr(Itr itr) {
        this.itr = itr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_crtrn", nullable=false, insertable=false, updatable=false)
    public Crtrn getCrtrn() {
        return this.crtrn;
    }
    
    public void setCrtrn(Crtrn crtrn) {
        this.crtrn = crtrn;
    }
    
    @Column(name="label", length=4000)
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    
    @Column(name="ndots")
    public Long getNdots() {
        return this.ndots;
    }
    
    public void setNdots(Long ndots) {
        this.ndots = ndots;
    }




}


