package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItrEntVl generated by hbm2java
 */
@Entity
@Table(name="itr_ent_vl"
    ,catalog="mca2"
)
public class ItrEntVl  implements java.io.Serializable {


     private Long idItrEntVl;
     private Itr itr;
     private SpcEnt spcEnt;
     private Float value;
     private Long objectId;
     private Long objectId2;

    public ItrEntVl() {
    }

    public ItrEntVl(Itr itr, SpcEnt spcEnt, Float value, Long objectId, Long objectId2) {
       this.itr = itr;
       this.spcEnt = spcEnt;
       this.value = value;
       this.objectId = objectId;
       this.objectId2 = objectId2;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_itr_ent_vl", unique=true, nullable=false)
    public Long getIdItrEntVl() {
        return this.idItrEntVl;
    }
    
    public void setIdItrEntVl(Long idItrEntVl) {
        this.idItrEntVl = idItrEntVl;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_itr")
    public Itr getItr() {
        return this.itr;
    }
    
    public void setItr(Itr itr) {
        this.itr = itr;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_ent")
    public SpcEnt getSpcEnt() {
        return this.spcEnt;
    }
    
    public void setSpcEnt(SpcEnt spcEnt) {
        this.spcEnt = spcEnt;
    }
    
    @Column(name="value", precision=12, scale=0)
    public Float getValue() {
        return this.value;
    }
    
    public void setValue(Float value) {
        this.value = value;
    }
    
    @Column(name="object_id")
    public Long getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }
    
    @Column(name="object_id2")
    public Long getObjectId2() {
        return this.objectId2;
    }
    
    public void setObjectId2(Long objectId2) {
        this.objectId2 = objectId2;
    }




}


