package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItrMsg generated by hbm2java
 */
@Entity
@Table(name="itr_msg"
    ,catalog="mca2"
)
public class ItrMsg  implements java.io.Serializable {


     private ItrMsgId id;
     private Itr itr;
     private Long msgType;
     private String txt;

    public ItrMsg() {
    }

	
    public ItrMsg(ItrMsgId id, Itr itr) {
        this.id = id;
        this.itr = itr;
    }
    public ItrMsg(ItrMsgId id, Itr itr, Long msgType, String txt) {
       this.id = id;
       this.itr = itr;
       this.msgType = msgType;
       this.txt = txt;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idItr", column=@Column(name="id_itr", nullable=false) ), 
        @AttributeOverride(name="seq", column=@Column(name="seq", nullable=false) ) } )
    public ItrMsgId getId() {
        return this.id;
    }
    
    public void setId(ItrMsgId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_itr", nullable=false, insertable=false, updatable=false)
    public Itr getItr() {
        return this.itr;
    }
    
    public void setItr(Itr itr) {
        this.itr = itr;
    }
    
    @Column(name="msg_type")
    public Long getMsgType() {
        return this.msgType;
    }
    
    public void setMsgType(Long msgType) {
        this.msgType = msgType;
    }
    
    @Column(name="txt", length=4000)
    public String getTxt() {
        return this.txt;
    }
    
    public void setTxt(String txt) {
        this.txt = txt;
    }




}


