package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItrMsgId generated by hbm2java
 */
@Embeddable
public class ItrMsgId  implements java.io.Serializable {


     private Long idItr;
     private Long seq;

    public ItrMsgId() {
    }

    public ItrMsgId(Long idItr, Long seq) {
       this.idItr = idItr;
       this.seq = seq;
    }
   

    @Column(name="id_itr", nullable=false)
    public Long getIdItr() {
        return this.idItr;
    }
    
    public void setIdItr(Long idItr) {
        this.idItr = idItr;
    }

    @Column(name="seq", nullable=false)
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItrMsgId) ) return false;
		 ItrMsgId castOther = ( ItrMsgId ) other; 
         
		 return ( (this.getIdItr()==castOther.getIdItr()) || ( this.getIdItr()!=null && castOther.getIdItr()!=null && this.getIdItr().equals(castOther.getIdItr()) ) )
 && ( (this.getSeq()==castOther.getSeq()) || ( this.getSeq()!=null && castOther.getSeq()!=null && this.getSeq().equals(castOther.getSeq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdItr() == null ? 0 : this.getIdItr().hashCode() );
         result = 37 * result + ( getSeq() == null ? 0 : this.getSeq().hashCode() );
         return result;
   }   


}


