package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prblm generated by hbm2java
 */
@Entity
@Table(name="prblm"
    ,catalog="mca2"
)
public class Prblm  implements java.io.Serializable {


     private Long idPrblm;
     private Prblm prblm;
     private Usr usr;
     private String snm;
     private String nm;
     private String dscr;
     private Date created;
     private Long NCols;
     private Long NRows;
     private Long NNzeros;
     private Long pblsh;
     private Set<Instnc> instncs = new HashSet<Instnc>(0);
     private Set<Prblm> prblms = new HashSet<Prblm>(0);
     private Set<Atrbt> atrbts = new HashSet<Atrbt>(0);

    public Prblm() {
    }

    public Prblm(Prblm prblm, Usr usr, String snm, String nm, String dscr, Date created, Long NCols, Long NRows, Long NNzeros, Long pblsh, Set<Instnc> instncs, Set<Prblm> prblms, Set<Atrbt> atrbts) {
       this.prblm = prblm;
       this.usr = usr;
       this.snm = snm;
       this.nm = nm;
       this.dscr = dscr;
       this.created = created;
       this.NCols = NCols;
       this.NRows = NRows;
       this.NNzeros = NNzeros;
       this.pblsh = pblsh;
       this.instncs = instncs;
       this.prblms = prblms;
       this.atrbts = atrbts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_prblm", unique=true, nullable=false)
    public Long getIdPrblm() {
        return this.idPrblm;
    }
    
    public void setIdPrblm(Long idPrblm) {
        this.idPrblm = idPrblm;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent")
    public Prblm getPrblm() {
        return this.prblm;
    }
    
    public void setPrblm(Prblm prblm) {
        this.prblm = prblm;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usr")
    public Usr getUsr() {
        return this.usr;
    }
    
    public void setUsr(Usr usr) {
        this.usr = usr;
    }
    
    @Column(name="snm", length=16)
    public String getSnm() {
        return this.snm;
    }
    
    public void setSnm(String snm) {
        this.snm = snm;
    }
    
    @Column(name="nm", length=128)
    public String getNm() {
        return this.nm;
    }
    
    public void setNm(String nm) {
        this.nm = nm;
    }
    
    @Column(name="dscr", length=2048)
    public String getDscr() {
        return this.dscr;
    }
    
    public void setDscr(String dscr) {
        this.dscr = dscr;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    
    @Column(name="n_cols")
    public Long getNCols() {
        return this.NCols;
    }
    
    public void setNCols(Long NCols) {
        this.NCols = NCols;
    }
    
    @Column(name="n_rows")
    public Long getNRows() {
        return this.NRows;
    }
    
    public void setNRows(Long NRows) {
        this.NRows = NRows;
    }
    
    @Column(name="n_nzeros")
    public Long getNNzeros() {
        return this.NNzeros;
    }
    
    public void setNNzeros(Long NNzeros) {
        this.NNzeros = NNzeros;
    }
    
    @Column(name="pblsh")
    public Long getPblsh() {
        return this.pblsh;
    }
    
    public void setPblsh(Long pblsh) {
        this.pblsh = pblsh;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prblm")
    public Set<Instnc> getInstncs() {
        return this.instncs;
    }
    
    public void setInstncs(Set<Instnc> instncs) {
        this.instncs = instncs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prblm")
    public Set<Prblm> getPrblms() {
        return this.prblms;
    }
    
    public void setPrblms(Set<Prblm> prblms) {
        this.prblms = prblms;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="prblm")
    public Set<Atrbt> getAtrbts() {
        return this.atrbts;
    }
    
    public void setAtrbts(Set<Atrbt> atrbts) {
        this.atrbts = atrbts;
    }




}


