package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SpcMthdDict generated by hbm2java
 */
@Entity
@Table(name="spc_mthd_dict"
    ,catalog="mca2"
)
public class SpcMthdDict  implements java.io.Serializable {


     private Long idMthd;
     private String snm;
     private String nm;
     private Long pblsh;
     private Long seq;
     private Set<SpcMthd> spcMthds = new HashSet<SpcMthd>(0);

    public SpcMthdDict() {
    }

	
    public SpcMthdDict(Long idMthd) {
        this.idMthd = idMthd;
    }
    public SpcMthdDict(Long idMthd, String snm, String nm, Long pblsh, Long seq, Set<SpcMthd> spcMthds) {
       this.idMthd = idMthd;
       this.snm = snm;
       this.nm = nm;
       this.pblsh = pblsh;
       this.seq = seq;
       this.spcMthds = spcMthds;
    }
   
     @Id 
    
    @Column(name="id_mthd", unique=true, nullable=false)
    public Long getIdMthd() {
        return this.idMthd;
    }
    
    public void setIdMthd(Long idMthd) {
        this.idMthd = idMthd;
    }
    
    @Column(name="snm", length=16)
    public String getSnm() {
        return this.snm;
    }
    
    public void setSnm(String snm) {
        this.snm = snm;
    }
    
    @Column(name="nm", length=128)
    public String getNm() {
        return this.nm;
    }
    
    public void setNm(String nm) {
        this.nm = nm;
    }
    
    @Column(name="pblsh")
    public Long getPblsh() {
        return this.pblsh;
    }
    
    public void setPblsh(Long pblsh) {
        this.pblsh = pblsh;
    }
    
    @Column(name="seq")
    public Long getSeq() {
        return this.seq;
    }
    
    public void setSeq(Long seq) {
        this.seq = seq;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="spcMthdDict")
    public Set<SpcMthd> getSpcMthds() {
        return this.spcMthds;
    }
    
    public void setSpcMthds(Set<SpcMthd> spcMthds) {
        this.spcMthds = spcMthds;
    }




}


