package bs.ecust.domain.db;
// Generated 2017-1-13 20:35:58 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usr generated by hbm2java
 */
@Entity
@Table(name="usr"
    ,catalog="mca2"
)
public class Usr  implements java.io.Serializable {


     private Long idUsr;
     private String login;
     private Long isDisabled;
     private String password;
     private Set<Instnc> instncs = new HashSet<Instnc>(0);
     private Set<Prblm> prblms = new HashSet<Prblm>(0);
     private Set<Anlz> anlzs = new HashSet<Anlz>(0);
     private Set<Itr> itrs = new HashSet<Itr>(0);

    public Usr() {
    }

    public Usr(String login, Long isDisabled, String password, Set<Instnc> instncs, Set<Prblm> prblms, Set<Anlz> anlzs, Set<Itr> itrs) {
       this.login = login;
       this.isDisabled = isDisabled;
       this.password = password;
       this.instncs = instncs;
       this.prblms = prblms;
       this.anlzs = anlzs;
       this.itrs = itrs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id_usr", unique=true, nullable=false)
    public Long getIdUsr() {
        return this.idUsr;
    }
    
    public void setIdUsr(Long idUsr) {
        this.idUsr = idUsr;
    }
    
    @Column(name="login", length=64)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    @Column(name="is_disabled")
    public Long getIsDisabled() {
        return this.isDisabled;
    }
    
    public void setIsDisabled(Long isDisabled) {
        this.isDisabled = isDisabled;
    }
    
    @Column(name="password", length=256)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<Instnc> getInstncs() {
        return this.instncs;
    }
    
    public void setInstncs(Set<Instnc> instncs) {
        this.instncs = instncs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<Prblm> getPrblms() {
        return this.prblms;
    }
    
    public void setPrblms(Set<Prblm> prblms) {
        this.prblms = prblms;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<Anlz> getAnlzs() {
        return this.anlzs;
    }
    
    public void setAnlzs(Set<Anlz> anlzs) {
        this.anlzs = anlzs;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usr")
    public Set<Itr> getItrs() {
        return this.itrs;
    }
    
    public void setItrs(Set<Itr> itrs) {
        this.itrs = itrs;
    }




}


